=== baptistem/VideoTek/XML/videotheque.dtd
<?xml version="1.0" encoding="UTF-8"?>
 
 <!ELEMENT videotheque (films)+>
 <!ELEMENT films (film)+>
 <!ELEMENT film  (titre,genre,annee,realisateur,acteurs,description)>
 <!ELEMENT titre (#PCDATA)>
 <!ELEMENT genre (#PCDATA)>
 <!ELEMENT annee (#PCDATA)>
 <!ELEMENT realisateur (#PCDATA)>
 <!ELEMENT acteurs (acteur)+>
 <!ELEMENT acteur (#PCDATA)>
 <!ELEMENT description (#PCDATA)>

=== baptistem/VideoTek/XML/db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videotheque SYSTEM "videotheque.dtd">
<videotheque>
	<films>
		<film>
			<titre>Le pas petit poucet</titre>
			<genre>Graille</genre>
			<realisateur>Christophe Campos</realisateur>
			<annee>2009</annee>
			<acteurs>
				<acteur>Omar Sy</acteur>
				<acteur>Fred Testo</acteur>
			</acteurs>
			<description>Papa Bûcheron et Maman Légère souhaitent se débarrasser de leurs 7 enfants, Grand Poucet, Jean Bedave, Jean Pakis, Jean Chong, Jean Ramon, Jean Kamel et Jean Doumé, qui leur coûtent trop cher.
                Ils décident de les perdre dans les bois, mais c'est sans compter l'intelligence du plus mal-aimé des enfants, Grand Poucet.</description>
            <media>http://www.commeaucinema.com/images/news_insert/_20651b1bce770077651c6b3040684e49.jpg</media>
		</film>
		<film>
			<titre>La cité de la peur</titre>
			<genre>Comédie, Policier</genre>
			<realisateur>Alain Chabat</realisateur>
			<annee>1994</annee>
			<acteurs>
				<acteur>Alain Chabat</acteur>
				<acteur>Chantale Lauby</acteur>
				<acteur>Gérard Darmond</acteur>
				<acteur>Dominique Farrugia</acteur>
			</acteurs>
			<description>Odile Deray, attachée de presse, vient au Festival de Cannes pour présenter le film "Red is Dead". Malheureusement, celui-ci est d'une telle faiblesse que personne ne souhaite en faire l'écho. Mais lorsque les projectionnistes du long-métrage en question meurent chacun leur tour dans d'étranges circonstances, "Red is dead" bénéficie d'une incroyable publicité. Serge Karamazov est alors chargé de protéger le nouveau projectionniste du film...</description>
            <media>http://fr.web.img2.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/18/35/86/35/19106159.jpg</media>
		</film>
		<film>
			<titre>Qui a tué Pamela Rose</titre>
			<genre>Comédie, Policier</genre>
			<realisateur>Eric Lartigau</realisateur>
			<annee>2003</annee>
			<acteurs>
				<acteur>Kad Merad</acteur>
				<acteur>Olivier Maroux</acteur>
				<acteur>Gérard Darmond</acteur>
			</acteurs>
			<description>Agents du FBI, Bullit et Riper enquêtent sur le meurtre de la jeune strip-teaseuse Pamela Rose, retrouvée assassinée dans une chambre d'hôtel à Bornsville, une petite ville américaine sans histoires. Tout les oppose et pourtant ils doivent faire équipe : Bullit est un homme de terrain aux méthodes peu banales, tandis que Riper est un instructeur consciencieux, prêt à assurer sa première enquête.
                Confrontés à une police locale plutôt hostile, ces deux agents maladroits et déjantés vont devoir arrêter le ou les meurtriers. Au fil de leurs recherches, Bullit et Riper font la connaissance de Ginger, la meilleure amie de Pamela Rose. Ils s'aperçoivent rapidement qu'elle en sait plus que ce qu'elle veut en dire...</description>
		    <media>http://fr.web.img1.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/00/02/54/35/affiche1.jpg</media>
        </film>
		<film>
			<titre>La tour Montparnasse Infernale</titre>
			<genre>Comédie</genre>
			<realisateur>Charles Nemes</realisateur>
			<annee>2001</annee>
			<acteurs>
				<acteur>Eric Judor</acteur>
				<acteur>Ramzy Bedia</acteur>
				<acteur>Marina Foès</acteur>
			</acteurs>
			<description>Un soir, suspendus au 52ème étage de la Tour Montparnasse, Eric et Ramzy, deux laveurs de carreaux, ont pris du retard dans leur travail.Pendant ce temps, la jolie Stéphanie attend son oncle, le puissant PDG du Groupe Lanceval, et ses fils, les actionnaires principaux, pour un conseil d'administration nocturne qui va se révéler bien mouvementé. En effet, un commando surentraîné investit l'immeuble, contrôle tous les accès et prend la famille Lanceval en otage. Stéphanie est en fait l'organisatrice du coup monté et convoite la fortune de son oncle qui la méprise depuis toujours. Stéphanie et ses hommes n'attendent plus que la main de la chère mère, dont les empreintes vont permettre d'actionner le mécanisme d'ouverture du coffre.Cependant, nos deux compères sont restés au sommet de la Tour et risquent bien de faire capoter le plan machiavélique de la belle.</description>
		    <media>http://fr.web.img1.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/00/00/00/89/69197630_af.jpg</media>
        </film>
		<film>
			<titre>Astérix et Obélix Mission cléopatre</titre>
			<genre>Comédie</genre>
			<realisateur>Alain Chabat</realisateur>
			<annee>2002</annee>
			<acteurs>
				<acteur>Gérard Depardieu</acteur>
				<acteur>Christian Clavier</acteur>
				<acteur>Jamel Debouze</acteur>
				<acteur>Monica Bellucci</acteur>
				<acteur>Alain Chabat</acteur>
			</acteurs>
			<description>Cléopâtre, la reine d’Égypte, décide, pour défier l'Empereur romain Jules César, de construire en trois mois un palais somptueux en plein désert. Si elle y parvient, celui-ci devra concéder publiquement que le peuple égyptien est le plus grand de tous les peuples. Pour ce faire, Cléopâtre fait appel à Numérobis, un architecte d'avant-garde plein d'énergie. S'il réussit, elle le couvrira d'or. S'il échoue, elle le jettera aux crocodiles.
                Celui-ci, conscient du défi à relever, cherche de l'aide auprès de son vieil ami Panoramix. Le druide fait le voyage en Égypte avec Astérix et Obélix. De son côté, Amonbofis, l'architecte officiel de Cléopâtre, jaloux que la reine ait choisi Numérobis pour construire le palais, va tout mettre en œuvre pour faire échouer son concurrent.</description>
		    <media>http://fr.web.img4.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/00/02/39/29/aff_asterix.jpg</media>
        </film>
        <film>
            <titre>Hunger Games</titre>
            <genre>Science fiction</genre>
            <realisateur>Gary Ross</realisateur>
            <annee>2012</annee>
            <acteurs>
                <acteur>Jennifer Lawrence</acteur>
                <acteur>Josh Hutcherson</acteur>
                <acteur>Lenny Kravitz</acteur>
            </acteurs>
            <description>Chaque année, dans les ruines de ce qui était autrefois l'Amérique du Nord, le Capitole, l'impitoyable capitale de la nation de Panem, oblige chacun de ses douze districts à envoyer un garçon et une fille - les "Tributs" - concourir aux Hunger Games. A la fois sanction contre la population pour s'être rebellée et stratégie d'intimidation de la part du gouvernement, les Hunger Games sont un événement télévisé national au cours duquel les tributs doivent s'affronter jusqu'à la mort. L'unique survivant est déclaré vainqueur.
                La jeune Katniss, 16 ans, se porte volontaire pour prendre la place de sa jeune sœur dans la compétition. Elle se retrouve face à des adversaires surentraînés qui se sont préparés toute leur vie. Elle a pour seuls atouts son instinct et un mentor, Haymitch Abernathy, qui gagna les Hunger Games il y a des années mais n'est plus désormais qu'une épave alcoolique. Pour espérer pouvoir revenir un jour chez elle, Katniss va devoir, une fois dans l'arène, faire des choix impossibles entre la survie et son humanité, entre la vie et l'amour...</description>
            <media>http://fr.web.img6.acsta.net/r_640_600/b_1_d6d6d6/medias/nmedia/18/85/51/91/20018884.jpg</media>
        </film>
        <film>
            <titre>Hunger Games - L'embrasement</titre>
            <genre>Science fiction</genre>
            <realisateur>Francis Lawrence</realisateur>
            <annee>2013</annee>
            <acteurs>
                <acteur>Jennifer Lawrence</acteur>
                <acteur>Josh Hutcherson</acteur>
                <acteur>Lenny Kravitz</acteur>
            </acteurs>
            <description>Katniss Everdeen est rentrée chez elle saine et sauve après avoir remporté la 74e édition des Hunger Games avec son partenaire Peeta Mellark.
                Puisqu’ils ont gagné, ils sont obligés de laisser une fois de plus leur famille et leurs amis pour partir faire la Tournée de la victoire dans tous les districts. Au fil de son voyage, Katniss sent que la révolte gronde, mais le Capitole exerce toujours un contrôle absolu sur les districts tandis que le Président Snow prépare la 75e édition des Hunger Games, les Jeux de l’Expiation – une compétition qui pourrait changer Panem à jamais…</description>
            <media>http://fr.web.img4.acsta.net/r_640_600/b_1_d6d6d6/pictures/210/453/21045319_2013101714250983.jpg</media>
        </film>
        <film>
            <titre>Supercondriaque</titre>
            <genre>Comédie</genre>
            <realisateur>Dany Boon</realisateur>
            <annee>2014</annee>
            <acteurs>
                <acteur>Dany Boon</acteur>
                <acteur>Alice Pol</acteur>
                <acteur>Kad Merad</acteur>
                <acteur>Jean-Yves Berteloot</acteur>
            </acteurs>
            <description>Romain Faubert est un homme seul qui, à bientôt 40 ans, n’a ni femme ni enfant. Le métier qu’il exerce, photographe pour dictionnaire médical en ligne, n’arrange rien à une hypocondrie maladive qui guide son style de vie depuis bien trop longtemps et fait de lui un peureux névropathe. Il a comme seul et véritable ami son médecin traitant, le Docteur Dimitri Zvenska, qui dans un premier temps a le tort de le prendre en affection, ce qu’il regrette aujourd’hui amèrement. Le malade imaginaire est difficilement gérable et Dimitri donnerait tout pour s’en débarrasser définitivement. Le docteur Zvenska pense avoir le remède qui le débarrassera en douceur de Romain Flaubert : l’aider à trouver la femme de sa vie. Il l’invite à des soirées chez lui, l’inscrit sur un site de rencontre, l’oblige à faire du sport, le coach même sur la manière de séduire et de se comporter avec les femmes. Mais découvrir la perle rare qui sera capable de le supporter et qui par amour l’amènera à surmonter enfin son hypocondrie s’avère plus ardu que prévu...</description>
